# Generated by Django 5.0 on 2024-05-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadMedia',
        ),
    ]
